migrate:
	python3 manage.py makemigrations && python3 manage.py migrate

run:
	python3 manage.py runserver

init:
	python3 -m venv venv && pip3 install -r ../requirements.txt

requirements:
	pip3 freeze > ../requirements.txt

